python train.py \
  --data_name redial \
  --alpha 0.5 \
  --beta 0.1 \
  --query_used_info c l d \
  --doc_used_info m pref \
  --bf16 \
  --negative_sample 16 \
  --learning_rate 5e-5 \
  --batch_size 10 \
  --wandb_project CORAL # (Optional) Remove this if you are not using wandb.